Repository guanshiyin28/Proyek-Monitoring-Kelompok-7, pull requests merged in 2024-12, with the labels that each got.

#1 add tables
  components/project_tables.php
  components/report_tables.php
Labels: duplicate

#7 update email
  components/author_tables.php
Labels: documentation, good first issue

#9 Staging
  components/author_tables.php
Labels: documentation, duplicate, enhancement, help wanted, good first issue

#10 Insert Email
  components/author_tables.php
Labels: documentation, duplicate, good first issue

#11 Deploy
  components/author_tables.php
Labels: documentation
